name: lineageOT-test
channels:
  - defaults
  - conda-forge
  - etetoolkit
dependencies:
  - anndata>=0.7.4
  - cvxopt>=1.2.0
  - ete3>=3.1.1
  - ete_toolchain>=3.0.0
  - jupyter>=1.0.0
  - networkx>=2.4
  - python-newick>=1.3.1
  - numpy>=1.19.1
  - pandas>=1.0.5
  - pip>=20.1.1
  - pot>=0.7.0
  - pip:
    - pytest
    - scanpy>=1.5.1

